### PR TITLE
NetworkX 2.4 compatibility: node -> nodes

### PR DESCRIPTION
**Pull request by mmilata**
G.node was removed in 2.4: https://networkx.github.io/documentation/latest/release/release_2.4.html

Other parts of lndmanage refer to G.nodes so it should probably work with 2.2 as well.

```
$ lndmanage status
Initializing node interface.
Initializing network graph.
Saved graph is too old. Fetching new one.
Traceback (most recent call last):
  File "/nix/store/q8il8a40aqrdhh6ncpvn9f9fwgmy6hc3-lndmanage-0.10.0/bin/.lndmanage-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/q8il8a40aqrdhh6ncpvn9f9fwgmy6hc3-lndmanage-0.10.0/lib/python3.7/site-packages/lndmanage/lndmanage.py", line 479, in main
    node = LndNode(config_file=config_file)
  File "/nix/store/q8il8a40aqrdhh6ncpvn9f9fwgmy6hc3-lndmanage-0.10.0/lib/python3.7/site-packages/lndmanage/lib/node.py", line 85, in __init__
    self.set_info()
  File "/nix/store/q8il8a40aqrdhh6ncpvn9f9fwgmy6hc3-lndmanage-0.10.0/lib/python3.7/site-packages/lndmanage/lib/node.py", line 297, in set_info
    active_only=False, public_only=False)
  File "/nix/store/q8il8a40aqrdhh6ncpvn9f9fwgmy6hc3-lndmanage-0.10.0/lib/python3.7/site-packages/lndmanage/lib/node.py", line 396, in get_open_channels
    'alias': self.network.node_alias(c.remote_pubkey),
  File "/nix/store/q8il8a40aqrdhh6ncpvn9f9fwgmy6hc3-lndmanage-0.10.0/lib/python3.7/site-packages/lndmanage/lib/network.py", line 168, in node_alias
    return self.graph.node[node_pub_key]['alias']
AttributeError: 'MultiDiGraph' object has no attribute 'node'
```

### CODE REVIEW

**Comment by bitromortac** [comment]
Thank you for the contribution! I'm thinking about adding networkx 2.4 as a dependency, as it is probably more performant than 2.2. Could you adapt to `networkx2.4` in the `requirements.txt` and `setup.py`? It would also be good to have a shorter commit message, not showing the error.

**Comment by mmilata** [comment]
Updated, PTAL.

Btw I'm running lndmanage with the following dependecies (was too lazy to setup venv) and so far it seems to work fine:
```
cycler-0.10.0
decorator-4.4.1
googleapis-common-protos-1.6.0
grpcio-1.27.1
grpcio-tools-1.27.1
kiwisolver-1.1.0
networkx-2.4
numpy-1.18.1
protobuf-3.7.1
pyparsing-2.4.6
python-dateutil-2.8.1
six-1.14.0
Pygments-2.5.2
```

**Comment by bitromortac** [comment]
Ah ok, good to know. I'm trying to stay conservative with the dependencies, but at some point I should update them. Thank you again!
